name: buscaminas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.11.1
  google_fonts: ^6.2.0
  animate_do: ^3.1.2
  intl: ^0.20.2
  audioplayers: ^6.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/PantallaInicial.mp4
    - assets/imagenes/Mina.png
    - assets/imagenes/Bomba.png
    - assets/sonidos/win.ogg
    - assets/sonidos/cancel.ogg
    - assets/sonidos/foil2.ogg
    - assets/sonidos/intentar.wav
    - assets/sonidos/resultados.wav
    - assets/sonidos/generic1.ogg
    - assets/sonidos/card1.ogg
    - assets/sonidos/casilla.wav
    - assets/sonidos/esplosion.wav
    - assets/sonidos/gameover.mp3
    - assets/sonidos/ganaste.wav
    - assets/imagenes/titulo.png

